# STRING FUNCTIONS

# SETUP BOOKS TABLE USING books.sql
SELECT * FROM books;

# CONCAT(STRING, STRING ...)
SELECT book_id,title,CONCAT(author_fname,' ',author_lname) as name, released_year, stock_quantity, pages FROM books;

# CONCAT_WS TAKES SEPARATOR AS FIRST ARGUMENT: CONCAT_WS(SEPARATOR, STRING, STRING...)
SELECT book_id,CONCAT_WS('-',title,author_fname,author_lname) as name FROM books;

# SUBSTRING (STRING, START-INDEX, END-INDEX) OR SHORT SUBSTR
SELECT SUBSTRING(title, 1,10) FROM books;
SELECT SUBSTRING(title, -3) FROM books; # START FROM END

# CONCAT WITH SUBSTRING
SELECT book_id,CONCAT(SUBSTRING(title, 1,10), '...') as title FROM books;

# REPLACE: IT WONT CHANGE TABLE DATA, JUST FOR DISPLAY PURPOSE
# REPLACE(STRING, WHAT WE WANT TO CHANGE, WITH WHAT WE WANT TO CHANGE)
# ITS CASE SENSITIVE
SELECT REPLACE('HELLO WORLD', 'WORLD', 'RAHUL!');
SELECT REPLACE('CHOUDHARY CHOUDHARY', ' ', ' & ');
SELECT REPLACE(title, ' ', '-') FROM books;
SELECT title FROM books; # title IS UNCHANGED

# REVERSE(STRING) JUST REVERSE
SELECT REVERSE('RAHUL CHOUDHARY');
SELECT REVERSE(author_fname) FROM books;
SELECT author_fname FROM books;

# CHAR_LENGTH(STRING) IT TELLS LENGTH OF STRING
SELECT CHAR_LENGTH('RAHUL');

# LENGTH(STRING) IT TELLS HOW MANY BYTES THIS CHAR TAKES
# 2 CHINES CHAR MIGHT RETURN 6 BYTES AS THEY TAKE MORE SPACE IN MEMORY
SELECT LENGTH('RAHUL');
SELECT CHAR_LENGTH(title) as title_length, title FROM books;

# UPPER(STRING) || UCASE(STRING) && LOWER(STRING) || LCASE(STRING)
SELECT UPPER('rahul');
SELECT UCASE('rahul');

SELECT LOWER('RAHUL');
SELECT LCASE('RAHUL');

SELECT UPPER(title) FROM books;

# INSERT(STRING, INDEX TO INSERT, NO OF CHAR TO REPLACE, STRING TO REPLACE WITH)
SELECT INSERT('HELLO BOBBY', 6, 0, ' THERE');
SELECT INSERT('HELLO BOBBY', 6, 4, ' THERE');

# LEFT(STRING,HOW MANY CHAR) && RIGHT(STRING, HOW MANY CHAR)
SELECT LEFT('OMG HAHA LOL', 3);
SELECT RIGHT('OMG HAHA LOL', 3);

SELECT title, LEFT(author_fname,1) as initial FROM books;

# REPEAT(STRING,REPEAT TIMES)
SELECT REPEAT('HA', 2);

# TRIM(STRING) IT REMOVE LEADING AND TRAILING SPACES NOT THE MIDDLE SPACE
SELECT TRIM('   RAHUL CHOUDHARY');
SELECT TRIM(LEADING '.' FROM '...RAHUL CHOUDHARY');
SELECT TRIM(TRAILING '.' FROM 'RAHUL CHOUDHARY...');
SELECT TRIM(BOTH '.' FROM '...RAHUL CHOUDHARY...');

# EXERCISE
SELECT UPPER(REVERSE(' Why does my cat look at me with such hatred?'));
SELECT REPLACE(title, ' ',  '->') FROM books;
SELECT author_lname AS forwards, REVERSE(author_lname) AS backwards FROM books;
SELECT CONCAT(UPPER(author_fname), ' ', UPPER(author_lname)) AS 'full name in caps' FROM books;
SELECT CONCAT(title, ' was released in ', released_year) AS blurb FROM books;
SELECT title, CHAR_LENGTH(title) AS 'character count' FROM books;
SELECT CONCAT(SUBSTRING(title,1,10), '...') AS short_title, CONCAT(author_lname,',',author_fname) AS author, CONCAT(stock_quantity, ' in stock') AS quantity FROM books;

