# STORING TEXT

# CHAR IS FASTER FOR FIXED LENGTH TEXT
# EX STATE ABBREVIATIONS , YES/NO, ZIP CODES
# OTHERWISE USE VARCHAR

# WE WILL GET DATA TOO LONG FOR COLUMN NAME... IF WE INSERT DATA MORE THEN WHAT WE SET LIKE CHAR(2) OR VARCHAR(2)

# NUMBERS
# TINYINT: -128 TO 127 : 1 BYTE
# SMALLINT: -32768 TO 32767 : 2 BYTE
# MEDIUMINT: -8388608 TO 8388607 : 3 BYTE
# INT: -2147483648 TO 2147483647 : 4 BYTE
# BIGINT: -2^63 TO 2^63-1 : 8 BYTE


CREATE TABLE parent (child TINYINT);
INSERT INTO parent VALUE (-3);

# IF WE CREATE TABLE USING KEYWORD UNSIGNED THEN MIN VALUE WILL START FROM 0
# NOT ALLOWED: Out of range value for column 'child' at row 1
DROP TABLE parent;
CREATE TABLE parent (child TINYINT UNSIGNED);
INSERT INTO parent VALUE (-3);

# DECIMAL(TOTAL-LENGTH,DECIMAL-LENGTH)
# FOR FINANCES WE NEED DECIMAL
# EX DECIMAL(5,2): 231.87 ( 3 BEFORE DECIMAL AND 2 AFTER DECIMAL ) : 999.99 IS MAX YOU CAN ALLOCATE
# 4381.3 WILL GIVE Out of range value for column : WE SAID 3 BEFORE AND 2 AFTER DECIMAL
# 5.026 WILL TRUNCATE & ROUND OFF AFTER 2 DECIMAL AND GIVE 5.03

# FLOAT & DOUBLE
# FLOAT: 4 BYTES: 7 DIGIT PRECISION
# DOUBLE: 8 BYTES: 15 DIGIT PRECISION
# FOR SPEED USE DOUBLE FOR PRECISION USE BIGINT

# DATES & TIME
# DATE YYYY-MM-DD
# TIME HH:MM:SS MAX RANGE -838:59:59 TO 838:59:59
# DATE TIME YYYY-MM-DD HH:MM:SS
CREATE DATABASE digital_ai;
USE digital_ai;

DROP TABLE people;
CREATE TABLE people (
                        name VARCHAR(100),
                        birthdate DATE,
                        birthtime TIME,
                        birthdt DATETIME
);

INSERT INTO people (name, birthdate, birthtime, birthdt)
VALUES ('Elton', '2000-12-25', '11:00:00', '2000-12-25 11:00:00');

INSERT INTO people (name, birthdate, birthtime, birthdt)
VALUES ('Lulu', '1985-04-11', '9:45:10', '1985-04-11 9:45:10');

INSERT INTO people (name, birthdate, birthtime, birthdt)
VALUES ('Juan', '2020-08-15', '23:59:00', '2020-08-15 23:59:00');

INSERT INTO people (name, birthdate, birthtime, birthdt)
VALUES ('Rahul', CURRENT_DATE(), CURRENT_TIME(), CURRENT_TIMESTAMP());

# SHORTER VERSION FOR ABOVE: BOTH ARE SAME
INSERT INTO people (name, birthdate, birthtime, birthdt)
VALUES ('Choudhary', CURDATE(), CURTIME(), NOW());

SELECT * FROM people;

# DATE TIME FUNCTIONS
SELECT CURDATE();
SELECT CURTIME();
SELECT NOW();

# FORMATTING DATE
SELECT birthdate FROM people;
SELECT birthdate, DAY(birthdate) AS DAY FROM people;
SELECT birthdate, DAY(birthdate) AS DAY,MONTH(birthdate) AS MONTH FROM people;
SELECT birthdate, DAY(birthdate) AS DAY,MONTH(birthdate) AS MONTH, YEAR(birthdate) AS YEAR FROM people;
SELECT birthdate, DAY(birthdate) AS DAY, DAYOFWEEK(birthdate) AS DAY_OF_WEEK, DAYOFMONTH(birthdate) AS DAY_OF_MONTH FROM people;
SELECT birthdate, MONTH(birthdate) AS MONTH, MONTHNAME(birthdate) AS MONTH_NAME FROM people;

# FORMATTING TIME
SELECT birthtime FROM people;
SELECT birthtime, HOUR(birthtime) AS BIRTH_HOUR, MINUTE(birthtime) AS BIRTH_MINUTE, SECOND(birthtime) AS BIRTH_SECOND FROM people;

# FORMATTING DATETIME
SELECT birthdt, YEAR(birthdt) AS YEAR, MONTH(birthdt) AS MONTH, DAY(birthdt) AS DAY,HOUR(birthdt) AS HOUR, MINUTE(birthdt) AS MINUTE, SECOND(birthdt) AS SECOND  FROM people;
SELECT CONCAT(MONTHNAME(birthdt), ' ', DAY(birthdt), ' ', YEAR(birthdt)) AS birthday FROM people;
SELECT birthdate, DATE_FORMAT(birthdate, '%a %b %e %Y') AS birthday FROM people;
SELECT birthdt, DATE_FORMAT(birthdt, '%H:%i') FROM people;
SELECT birthdt, DATE_FORMAT(birthdt, 'BORN ON: %r') FROM people;

# DATE MATH
SELECT birthdate,DATEDIFF(CURDATE(),birthdate) AS DIFF FROM people;
SELECT birthtime,TIMEDIFF(CURTIME(),birthtime) AS DIFF FROM people;

SELECT NOW() AS Today,DATE_ADD(NOW(), INTERVAL 1 YEAR ) AS ADD_1_YEAR;
SELECT NOW() AS Today,DATE_ADD(NOW(), INTERVAL 1 MONTH ) AS ADD_1_MONTH;
SELECT NOW() AS Today,DATE_ADD(NOW(), INTERVAL 1 DAY) AS ADD_1_DAY;
SELECT NOW() AS Today,DATE_ADD(NOW(), INTERVAL 1 HOUR ) AS ADD_1_HOUR;
SELECT NOW() AS Today,DATE_ADD(NOW(), INTERVAL 1 MINUTE ) AS ADD_1_MINUTE;
SELECT NOW() AS Today,DATE_ADD(NOW(), INTERVAL 1 SECOND ) AS ADD_1_SECOND;

SELECT NOW() AS Today,DATE_SUB(NOW(), INTERVAL 1 YEAR ) AS SUB_1_YEAR;
SELECT NOW() AS Today,DATE_SUB(NOW(), INTERVAL 1 MONTH ) AS SUB_1_MONTH;
SELECT NOW() AS Today,DATE_SUB(NOW(), INTERVAL 1 DAY) AS SUB_1_DAY;
SELECT NOW() AS Today,DATE_SUB(NOW(), INTERVAL 1 HOUR ) AS SUB_1_HOUR;
SELECT NOW() AS Today,DATE_SUB(NOW(), INTERVAL 1 MINUTE ) AS SUB_1_MINUTE;
SELECT NOW() AS Today,DATE_SUB(NOW(), INTERVAL 1 SECOND ) AS SUB_1_SECOND;


SELECT NOW() - INTERVAL 32 YEAR;
SELECT NOW() + INTERVAL 32 YEAR;
SELECT YEAR(NOW() + INTERVAL 32 YEAR) as AFTER_32_YEAR ;

# DATETIME VS TIMESTAMP
# TIMESTAMP TAKES LESS SPACE BECAUSE ITS RANGE IS 1970-01-01 00:00:00 UTC TO 2038-01-19 03:14:07 UTC
# DATETIME TAKES MORE SPACE ITS RANGE IS 1000-01-01 00:00:00 TO 9999-12-31 23:59:59

CREATE TABLE captions (text VARCHAR(150), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO captions (text) VALUES ('MALTA TRIP'), ('FRANCE TRIP');
INSERT INTO captions (text) VALUES ('GERMANY TRIP');
SELECT * FROM captions;

CREATE TABLE comments (text VARCHAR(150), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
INSERT INTO comments (text) VALUES ('MALTA TRIP'), ('FRANCE TRIP');
INSERT INTO comments (text) VALUES ('GERMANY TRIP');
SELECT * FROM comments;
UPDATE comments SET text='FIRST TRIP WAS TO MALTA' WHERE text='MALTA TRIP';
SELECT * FROM comments;

# EXERCISE
SELECT CURTIME();
SELECT CURDATE();
SELECT DAYOFWEEK(NOW()), DAYNAME(NOW());
SELECT CONCAT(MONTH(NOW()),'/',DAY(NOW()),'/',YEAR(NOW()));
SELECT DATE_FORMAT(CURDATE(), '%m/%d/%Y');
SELECT DATE_FORMAT(NOW(), '%M %D at %h:%i');